version: "3.7"

services:
  ringtoolsweb:
    image: ghcr.io/dsbaars/ringtools-web-umbrel:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 5000:5000
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      CERT: "/lnd/tls.cert"
      MACAROON: "/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/readonly.macaroon"
      LNDHOST: "$LND_IP:$LND_GRPC_PORT"